from pathlib import Path
from typing import Any, Dict, List, Optional

import openpyxl
import pyodbc

from pipeline_dimensional_data import config
from utils import get_database_connection


SHEET_TO_TABLE = {
    "Categories": "Staging_Categories",
    "Customers": "Staging_Customers",
    "Employees": "Staging_Employees",
    "OrderDetails": "Staging_Order_Details",
    "Orders": "Staging_Orders",
    "Products": "Staging_Products",
    "Region": "Staging_Region",
    "Shippers": "Staging_Shippers",
    "Suppliers": "Staging_Suppliers",
    "Territories": "Staging_Territories",
}


DELETE_ORDER = [
    "Staging_Order_Details",
    "Staging_Orders",
    "Staging_Territories",
    "Staging_Products",
    "Staging_Suppliers",
    "Staging_Shippers",
    "Staging_Region",
    "Staging_Employees",
    "Staging_Customers",
    "Staging_Categories",
]


def get_connection() -> pyodbc.Connection:
    """
    Creates a SQL Server connection using sql_server_config.cfg.

    sql_server_config.cfg is created locally from sql_server_config_template.cfg
    and should not contain real credentials in GitHub.
    """
    return get_database_connection(
        config_file_path=str(config.CONFIG_FILE_PATH),
        section_name=config.CONFIG_SECTION_NAME,
    )


def clean_headers(headers: List[Any]) -> List[Optional[str]]:
    """
    Cleans Excel header values.

    Empty header cells are returned as None and ignored later.
    """
    return [
        str(header).strip() if header is not None else None
        for header in headers
    ]


def load_excel_to_staging(raw_data_file_path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Loads the Excel source data into SQL Server staging tables.

    Expected Excel file:
        data/raw/raw_data_source.xlsx

    The staging_raw_id_sk column is not inserted manually because it is an
    IDENTITY column generated by SQL Server.
    """
    if raw_data_file_path is None:
        raw_data_file_path = config.RAW_DATA_FILE_PATH

    raw_data_file_path = Path(raw_data_file_path)

    if not raw_data_file_path.exists():
        raise FileNotFoundError(
            f"Raw data file was not found: {raw_data_file_path}"
        )

    workbook = openpyxl.load_workbook(
        raw_data_file_path,
        data_only=True,
    )

    missing_sheets = [
        sheet_name
        for sheet_name in SHEET_TO_TABLE
        if sheet_name not in workbook.sheetnames
    ]

    if missing_sheets:
        raise ValueError(f"Missing Excel sheets: {missing_sheets}")

    connection = get_connection()
    cursor = connection.cursor()

    loaded_rows = {}

    try:
        # Clear staging tables first, so each run starts from the same raw data state.
        for table_name in DELETE_ORDER:
            cursor.execute(f"DELETE FROM dbo.{table_name};")
            cursor.execute(f"DBCC CHECKIDENT ('dbo.{table_name}', RESEED, 0);")

        for sheet_name, table_name in SHEET_TO_TABLE.items():
            worksheet = workbook[sheet_name]
            rows = list(worksheet.iter_rows(values_only=True))

            if not rows:
                loaded_rows[table_name] = 0
                continue

            headers = clean_headers(list(rows[0]))

            valid_indexes = [
                index
                for index, header in enumerate(headers)
                if header
            ]

            headers = [headers[index] for index in valid_indexes]

            cleaned_rows = []

            for row in rows[1:]:
                values = [
                    row[index] if index < len(row) else None
                    for index in valid_indexes
                ]

                if all(value is None for value in values):
                    continue

                cleaned_rows.append(values)

            # Do not insert identity column if it exists in the Excel file.
            if "staging_raw_id_sk" in headers:
                identity_index = headers.index("staging_raw_id_sk")
                headers.pop(identity_index)
                cleaned_rows = [
                    row[:identity_index] + row[identity_index + 1:]
                    for row in cleaned_rows
                ]

            column_names = ", ".join(f"[{column}]" for column in headers)
            placeholders = ", ".join("?" for _ in headers)

            insert_sql = (
                f"INSERT INTO dbo.{table_name} ({column_names}) "
                f"VALUES ({placeholders});"
            )

            if cleaned_rows:
                cursor.fast_executemany = True
                cursor.executemany(insert_sql, cleaned_rows)

            loaded_rows[table_name] = len(cleaned_rows)

        connection.commit()

        return {
            "success": True,
            "task_name": "load_excel_to_staging",
            "source_file": str(raw_data_file_path),
            "loaded_rows": loaded_rows,
        }

    except Exception:
        connection.rollback()
        raise

    finally:
        cursor.close()
        connection.close()
